# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Comment environment in PR

on:
  pull_request:
    branches:
      - main

jobs:
  comment_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: "Integration branch URL: https://next-template-dyna-${{ github.head_ref }}.bdm-dev.dts-stn.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
